jobs:
- job: Build
  displayName: Build
  pool:
    vmImage: ubuntu-latest 
  variables:
    image_Repo: "iiq-base-bali-test" #name of the image
    container_Registry: "IGARegistry" #resource
  steps: # '-' => list
  - task: DownloadPackage@1
    displayName: Download Apache Tomcat 9.0.64
    inputs:
      packageType: 'upack'
      feed: 'fdeb977b-da18-4469-b9a6-938366a207c4/SP-FEED'
      definition: 'tomcat'
      version: '*'
      downloadPath: './hambali/app/src/common/dockerfiles/base'     
  - task: Docker@2
    displayName: Build and push image to container registry
    inputs:
      command: 'buildAndPush'
      containerRegistry: 'SP Registry' #connection?
      repository: $(image_Repo)
      Dockerfile: './hambali/app/src/common/dockerfiles/base/Dockerfile'
      tags: latest