jobs:
  - deployment: Deploy
    displayName: "Deploy to DEV"
    variables:
      aks_ResourceGroup: rg-cmn-identity-aks-sp
      aks_Cluster: aks-iga-sp
    environment: 'IGA-DEV.default'
    pool:
      vmImage: ubuntu-latest
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'manifests'
                targetPath: '$(Pipeline.Workspace)/manifests'

            - task: Docker@2
              displayName: Login to ACR
              inputs:
                command: login
                containerRegistry: "SP Registry"

            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                namespace: 'default'
                kubernetesServiceConnection: 'SP Kubernetes'
                manifests: |
                  $(Pipeline.Workspace)/manifests/deployment.yml
                  $(Pipeline.Workspace)/manifests/service.yml

            - task: Docker@2
              displayName: Logout to ACR
              inputs:
                command: logout
                containerRegistry: "SP Registry"