apiVersion: v1 # String
kind: Pod # String
metadata: # Dictionary
  name: myapp-pod
  labels: # Dictionary
    app: myapp  # Key value paids
spec:
  containers: # List
    - name: myapp
      # image: stacksimplify/kubenginx:1.0.0
      image: hambali999/kubenginx:1.0.0
      ports: 
        - containerPort: 80